name: Vhezly Discord Notifications

jobs:
  youtube_notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new YouTube Livestreams
        uses: actionsflow/actionsflow-action@v1
        with:
          config: |
            triggers:
              rss:
                url: hhttps://www.youtube.com/@Vhezly
            jobs:
              live_notifications:
                if: "contains(trigger.outputs.title, 'LIVE')"
                runs:
                  - run: |
                      curl -X POST -H "Content-Type: application/json" \
                      -d "{\"content\": \"🚨 **Vhezly IST LIVE!** 🚨 Kommt vorbei! ❤️ [{{ title }}]({{ link }})\"}" \
                      https://discord.com/api/webhooks/1336065545346355240/akFOkFka9btlWZ4p98u4CvRpWQSWLWuAokyds4xZBzcFjZ0HQnoqz8zlMTO1oH5Z9Wsc
              video_notifications:
                if: "!contains(trigger.outputs.title, 'LIVE')"
                runs:
                  - run: |
                      curl -X POST -H "Content-Type: application/json" \
                      -d "{\"content\": \"🍿 **Neues Video von Vhezly!** 🎬 [{{ title }}]({{ link }})\"}" \
                      https://discord.com/api/webhooks/1336066232742576279/sdI-2E77bNOnaQfhgBZZ09koeb5b4OYbE0hZVuAxW7sM2kj4r5OWwHjBt3d34Xa0k-aq
